In [1]:
import OpenAIGymAPI as api
import numpy as np
import scipy as sp
import spike
import gym

## Generate Dummy Data

In [2]:
time, activity, abs_activity, median_abs_deviations, channel_MAD = spike.start_to_finish()

In [3]:
len(time)

1024

In [4]:
activity

array([[-0.05354868,  0.05921079, -0.0647863 , ..., -0.00057487,
         0.00048587, -0.00040305],
       [ 0.0010158 , -0.00091568,  0.0007956 , ..., -0.00745175,
         0.00609948, -0.00491346],
       [-0.04333528,  0.04238572, -0.04135464, ..., -0.00083699,
         0.00069962, -0.00057556],
       ...,
       [ 0.02199666, -0.02135471,  0.02060896, ..., -0.00636923,
         0.00524539, -0.00425074],
       [ 0.0368769 , -0.03710024,  0.03728322, ...,  0.00220977,
        -0.00181884,  0.00147303],
       [ 0.03810144, -0.04059495,  0.04307691, ..., -0.00085991,
         0.00073784, -0.00062119]])

In [5]:
channel_MAD

array([[0.05352061, 0.05915547, 0.06474235, ..., 0.00058446, 0.00049704,
        0.00040923],
       [0.00100663, 0.00084864, 0.00068912, ..., 0.00747762, 0.00616606,
        0.00496234],
       [0.04335297, 0.04234007, 0.04130204, ..., 0.00083957, 0.00070551,
        0.00057964],
       ...,
       [0.02197937, 0.02123157, 0.02046291, ..., 0.0063956 , 0.00530258,
        0.00428969],
       [0.03688387, 0.03707861, 0.03725748, ..., 0.00221905, 0.00183888,
        0.00148669],
       [0.03808276, 0.04058306, 0.04307353, ..., 0.00086997, 0.00075062,
        0.00062863]])

In [6]:
def get_action_from_dummy_data(abs_activity, median_abs_deviations):
    """
    Use the dummy neural activity to decide an action for CartPole.
    """
    # Aggregate spike activity across channels (e.g., summing or averaging)
    # spike_counts = spike.count_spikes(abs_activity, median_abs_deviations)
    spike_counts = np.sum(abs_activity, axis=1)
    # Use only the first two channels to decide the action
    logits = spike_counts[:2]  # Extract the first two channels
    probabilities = sp.special.softmax(logits)  # Convert to probabilities using softmax
    action = np.argmax(probabilities)  # Choose the action with the highest probability
    
    return action, probabilities

In [7]:
abs_activity

array([[0.05354868, 0.05921079, 0.0647863 , ..., 0.00057487, 0.00048587,
        0.00040305],
       [0.0010158 , 0.00091568, 0.0007956 , ..., 0.00745175, 0.00609948,
        0.00491346],
       [0.04333528, 0.04238572, 0.04135464, ..., 0.00083699, 0.00069962,
        0.00057556],
       ...,
       [0.02199666, 0.02135471, 0.02060896, ..., 0.00636923, 0.00524539,
        0.00425074],
       [0.0368769 , 0.03710024, 0.03728322, ..., 0.00220977, 0.00181884,
        0.00147303],
       [0.03810144, 0.04059495, 0.04307691, ..., 0.00085991, 0.00073784,
        0.00062119]])

In [8]:
action, probabilities = get_action_from_dummy_data(abs_activity, median_abs_deviations)
probabilities

array([0.00614082, 0.99385918])

In [ ]:
episodes = 100
scores = []
env = gym.make('CartPole-v1', render_mode="human") 
for e in range(episodes):  
    state, _ = env.reset()
    done, score = False, 0
    while not done:
        time, activity, abs_activity, median_abs_deviations, channel_MAD = spike.start_to_finish()
        action, probabilities = get_action_from_dummy_data(abs_activity, median_abs_deviations)
        next_state, reward, done, _, _ = env.step(action)
        score += reward
        if done:
            scores.append(score)
            if not e % 10:
                print(f"episode: {e}/{episodes}, score: {score}")
        print(f"State: {state}")
        print(f"Action Taken: {action} ('0' = Left, '1' = Right)")
        print(f"Next State: {next_state}")
        print(f"Reward: {reward}")
        print(f"Done: {done}")


State: [-0.03041197  0.04497393  0.02462329  0.0220069 ]
Action Taken: 0 ('0' = Left, '1' = Right)
Next State: [-0.02951249 -0.15049233  0.02506343  0.32235593]
Reward: 1.0
Done: False
State: [-0.03041197  0.04497393  0.02462329  0.0220069 ]
Action Taken: 1 ('0' = Left, '1' = Right)
Next State: [-0.03252234  0.04426392  0.03151055  0.03768118]
Reward: 1.0
Done: False
State: [-0.03041197  0.04497393  0.02462329  0.0220069 ]
Action Taken: 0 ('0' = Left, '1' = Right)
Next State: [-0.03163706 -0.1512954   0.03226417  0.3401371 ]
Reward: 1.0
Done: False
State: [-0.03041197  0.04497393  0.02462329  0.0220069 ]
Action Taken: 0 ('0' = Left, '1' = Right)
Next State: [-0.03466297 -0.3468612   0.03906691  0.6428172 ]
Reward: 1.0
Done: False
State: [-0.03041197  0.04497393  0.02462329  0.0220069 ]
Action Taken: 0 ('0' = Left, '1' = Right)
Next State: [-0.04160019 -0.54250526  0.05192326  0.94754213]
Reward: 1.0
Done: False
State: [-0.03041197  0.04497393  0.02462329  0.0220069 ]
Action Taken: 0 ('

KeyboardInterrupt: 

: 

In [37]:
pip install pygame


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
